const nikeTrackSpikes = [
  {
    name: 'Nike Maxfly 2',
    event: 'Sprinting',
    price: 190.0,
    color: 'Multiple',
    image: 'maxfly_2.jpg',
    url: 'https://www.nike.com/t/maxfly-2-track-field-sprinting-spikes',
  },
  {
    name: 'Nike Victory 2',
    event: 'Distance',
    price: 190.0,
    color: 'Multiple',
    image: 'victory_2.jpg',
    url: 'https://www.nike.com/t/victory-2-track-field-distance-spikes',
  },
  {
    name: 'Nike Dragonfly 2 Elite',
    event: 'Distance',
    price: 190.0,
    color: 'Multiple',
    image: 'dragonfly_2_elite.jpg',
    url: 'https://www.nike.com/t/dragonfly-2-elite-track-field-distance-spikes',
  },
  {
    name: 'Nike Dragonfly 2',
    event: 'Distance',
    price: 160.0,
    color: 'Multiple',
    image: 'dragonfly_2.jpg',
    url: 'https://www.nike.com/t/dragonfly-2-track-field-distance-spikes',
  },
  {
    name: 'Nike Superfly Elite 2',
    event: 'Sprinting',
    price: 160.0,
    color: 'Multiple',
    image: 'superfly_elite_2.jpg',
    url: 'https://www.nike.com/t/superfly-elite-2-track-field-sprinting-spikes',
  },
  {
    name: 'Nike Rival Sprint',
    event: 'Sprinting',
    price: 75.0,
    color: 'Multiple',
    image: 'rival_sprint.jpg',
    url: 'https://www.nike.com/t/rival-sprint-track-field-sprinting-spikes',
  },
  {
    name: 'Nike Rival Multi',
    event: 'Multi-Event',
    price: 75.0,
    color: 'Multiple',
    image: 'rival_multi.jpg',
    url: 'https://www.nike.com/t/rival-multi-track-field-multi-event-spikes',
  },
  {
    name: 'Nike Zoom Superfly Elite',
    event: 'Sprinting (100m-400m)',
    price: 150.0,
    color: 'Multiple',
    image: 'zoom_superfly_elite.jpg',
    url: 'https://www.runningwarehouse.com/catpage-MRSNIKC.html',
  },
  {
    name: 'Nike Zoom High Jump Elite',
    event: 'High Jump',
    price: 125.0,
    color: 'Multiple',
    image: 'zoom_high_jump_elite.jpg',
    url: 'https://www.runningwarehouse.com/catpage-MRSNIKC.html',
  },
  {
    name: 'Nike Zoom Rival Distance',
    event: 'Distance (400m-5K)',
    price: 65.0,
    color: 'Multiple',
    image: 'zoom_rival_distance.jpg',
    url: 'https://www.runningwarehouse.com/catpage-MRSNIKC.html',
  },
  {
    name: 'Nike Zoom Ja Fly',
    event: 'Sprinting (100m-400m)',
    price: 110.0,
    color: 'Multiple',
    image: 'zoom_ja_fly.jpg',
    url: 'https://www.runningwarehouse.com/catpage-MRSNIKC.html',
  },
  {
    name: 'Nike Zoom Rival Sprint',
    event: 'Sprinting (100m-400m)',
    price: 65.0,
    color: 'Multiple',
    image: 'zoom_rival_sprint.jpg',
    url: 'https://www.runningwarehouse.com/catpage-MRSNIKC.html',
  },
  {
    name: 'Nike Zoom Rival SD',
    event: 'Shot Put, Discus, Hammer Throw',
    price: 65.0,
    color: 'Multiple',
    image: 'zoom_rival_sd.jpg',
    url: 'https://www.runningwarehouse.com/catpage-MRSNIKC.html',
  },
  {
    name: 'Nike Zoom Rotational Throw',
    event: 'Shot Put, Discus, Hammer Throw',
    price: 120.0,
    color: 'Multiple',
    image: 'zoom_rotational_throw.jpg',
    url: 'https://www.runningwarehouse.com/catpage-MRSNIKC.html',
  },
  {
    name: 'Nike Zoom Triple Jump Elite',
    event: 'Triple Jump',
    price: 150.0,
    color: 'Multiple',
    image: 'zoom_triple_jump_elite.jpg',
    url: 'https://www.runningwarehouse.com/catpage-MRSNIKC.html',
  },
  {
    name: 'Nike Pole Vault Elite',
    event: 'Pole Vault',
    price: 150.0,
    color: 'Multiple',
    image: 'pole_vault_elite.jpg',
    url: 'https://www.runningwarehouse.com/catpage-MRSNIKC.html',
  },
  {
    name: 'Nike Zoom SD Throw',
    event: 'Shot Put, Discus, Hammer Throw',
    price: 100.0,
    color: 'Multiple',
    image: 'zoom_sd_throw.jpg',
    url: 'https://www.runningwarehouse.com/catpage-MRSNIKC.html',
  },
  {
    name: 'Nike Zoom Rival Jump',
    event: 'Long Jump, Triple Jump',
    price: 65.0,
    color: 'Multiple',
    image: 'zoom_rival_jump.jpg',
    url: 'https://www.runningwarehouse.com/catpage-MRSNIKC.html',
  },
]
export { nikeTrackSpikes }
